version: '2.1'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: ./
    ports:
      - "4444:4444"
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - "redis:redis"
    environment:
      - REDIS_URL=redis://redis:6379
    command: ./manage.py runserver 0.0.0.0:8000
