# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Comptoir',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='comptoir',
        ),
    ]
