# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('first_connexion', models.DateTimeField(auto_now_add=True)),
                ('last_event', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexion', to='website.Room')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='connexionrecord',
            unique_together=set([('room', 'user')]),
        ),
    ]
