# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160807_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comptoir',
            new_name='aComptoir',
        ),
    ]
