# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160809_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndergroundComptoir',
            fields=[
                ('acomptoir_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.aComptoir')),
                ('keyprint', models.CharField(blank=True, max_length=60, null=True)),
            ],
            bases=('website.acomptoir',),
        ),
    ]
