# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_undergroundcomptoir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='acomptoir',
            name='label',
        ),
        migrations.AddField(
            model_name='presence',
            name='comptoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aComptoir'),
        ),
        migrations.AddField(
            model_name='presence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set([('comptoir', 'channel_name')]),
        ),
    ]
