# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20161115_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='handle',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
