# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_acomptoir_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
